services:
  mongo:
    image: mongo:7
    container_name: naboo-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: naboo-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongo

volumes:
  mongo_data:
